spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vamptasiadb?serverTimezone=Europe/Madrid
    username: backend
    password: backend1234
  jpa:
    database: mysql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always